---
- name: Install and configure Nginx on AWS
  hosts: all
  become: yes # Run tasks with sudo privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Check if Nginx service is running
      shell: systemctl is-active nginx
      register: nginx_status
      changed_when: false

    - name: Show Nginx service status
      debug:
        msg: "Nginx service is {{ nginx_status.stdout }}"
